### ISSUE TITLE
Need help on using boosted yaml in java fx?

### ISSUE THREAD

**Issue by GaMeIsNtOvEr** [dejvokep/boosted-yaml#11]
Hey there.
I'm having some problems with boostedyaml setup in JavaFX.
I cannot find the boostedyaml module name in module-info.java
I've already done the pom.xml setup but now i need the boostedyaml name for the module-info.java

**Comment by dejvokep** [comment]
Hey, sorry for late reply, are you sure that your Maven side is all correctly set up? We are talking about Maven JavaFX modular application, right? Could you please leave a message on Discord?
