### ISSUE TITLE
Out-of-the-box Adventure support

### ISSUE THREAD

**Issue by marlester-dev** [dejvokep/boosted-yaml#35]
Would it be possible to support kyori adventure and minimessage out of the box?

**Comment by dejvokep** [comment]
Hello,

Unfortunately, there is no plan to support platform or implementation-specific tools and libraries out of the box. However, being able to save/retrieve instances of the dependencies mentioned above, should, by the looks of it, only require a few `TypeAdapters` (corresponding to the types you would like to support) which would use the built-in Adventure serializers.

Should you need any help, I will more than happily assist you.

Have a great day.
~ dejvokep
