### ISSUE TITLE
Avoid Shading Annotation Dependencies into JAR

### ISSUE THREAD

**Issue by Xiao-MoMi** [dejvokep/boosted-yaml#38]
Hi there, I noticed that the current build process shades annotation dependencies directly into the JAR file. This can lead to several issues.

**Comment by dejvokep** [comment]
Hello,

Thank you for reporting, I most likely forgot to put it there and haven't touched it ever since. Changed by #39, will be a part of the following release.

Have a nice one!
~ dejvokep
